#!/bin/bash

set -e

cd $(dirname $0)/..
PACKAGE=./gopath/src/$(<.package)
if [ -L "${PACKAGE}" ]; then
    rm ${PACKAGE}
fi

if [ ! -e "${PACKAGE}" ]; then
    mkdir -p $(dirname ${PACKAGE})
    ln -s $(pwd) ${PACKAGE}
fi

export GOPATH="$(pwd)/Godeps/_workspace:$(pwd)/gopath"

GITCOMMIT=$(git rev-parse --short HEAD)

mkdir -p bin
echo Building Cowbell
go build  -o bin/cowbell -a -tags "netgo" -installsuffix netgo -ldflags "-extldflags -static -X main.GITCOMMIT $GITCOMMIT"
